[Settings]
  ID = "covidcaremap"

[build]
  base    = "."
  publish = "_site"
  command = "./scripts/cibuild"
  environment = { COVID19_DEBUG = "1" }

[context.deploy-preview]
  environment = { JEKYLL_ENV = "staging" }

[context.production]
  environment = { JEKYLL_ENV = "production" }

[[redirects]]
  from = "https://covidcaremap.netlify.com/*"
  to = "https://www.covidcaremap.org/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "no-referrer"
